name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Instalar dependências
        run: npm ci

      - name: Build dos pacotes (Turborepo)
        run: npm run build

      - name: Build do Storybook
        working-directory: ./packages/docs
        run: npm run build-storybook

      - name: Criar .nojekyll
        run: touch ./packages/docs/storybook-static/.nojekyll

      - name: Deploy do Storybook
        working-directory: ./packages/docs
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
